<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Page;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pages = [
             [
                'page_name'        => 'About Us',
                'page_title'       => 'About Us',
                'page_slug'        => 'about-us',
                'page_description' => 'This is About Us Page',
                'meta_title'       => 'about-us',
                'keywords'         => 'about, company, info',
                'meta_description' => 'This is About Us page',
                'status'           => 1,
                'is_default'       => 1,
                'created_by'       => 1,
                'position'         => 2,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Introduction',
                'page_title'       => 'Introduction',
                'page_slug'        => 'introduction',
                'page_description' => 'Introduction to our organization.',
                'meta_title'       => 'introduction',
                'keywords'         => 'about,introduction',
                'meta_description' => 'Introduction page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 3,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'DECF Family',
                'page_title'       => 'DECF Family',
                'page_slug'        => 'decf-family',
                'page_description' => 'About our DECF Family.',
                'meta_title'       => 'decf-family',
                'keywords'         => 'decf,family',
                'meta_description' => 'DECF Family page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 4,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Testimonial',
                'page_title'       => 'Testimonial',
                'page_slug'        => 'testimonial',
                'page_description' => 'What our clients say.',
                'meta_title'       => 'testimonial',
                'keywords'         => 'testimonial,review',
                'meta_description' => 'Client testimonials',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 5,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'DECF in Media',
                'page_title'       => 'DECF in Media',
                'page_slug'        => 'decf-in-media',
                'page_description' => 'Our appearance in media.',
                'meta_title'       => 'decf-in-media',
                'keywords'         => 'media,decf',
                'meta_description' => 'DECF media coverage',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 6,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Strategic Action Plan',
                'page_title'       => 'Strategic Action Plan',
                'page_slug'        => 'strategic-action-plan',
                'page_description' => 'Our future plans and goals.',
                'meta_title'       => 'strategic-action-plan',
                'keywords'         => 'strategy,plan',
                'meta_description' => 'Strategic action plan page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 7,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'How To Reach Us',
                'page_title'       => 'How To Reach Us',
                'page_slug'        => 'how-to-reach-us',
                'page_description' => 'Find our location and contact details.',
                'meta_title'       => 'how-to-reach-us',
                'keywords'         => 'contact,location,map',
                'meta_description' => 'Reach us page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 8,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Services',
                'page_title'       => 'Services',
                'page_slug'        => 'services',
                'page_description' => 'Overview of our services.',
                'meta_title'       => 'services',
                'keywords'         => 'services,hospital,community',
                'meta_description' => 'List of all services',
                'status'           => 1,
                'is_default'       => 1,
                'created_by'       => 1,
                'position'         => 9,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Hospital Services',
                'page_title'       => 'Hospital Services',
                'page_slug'        => 'hospital-services',
                'page_description' => 'Details about hospital services.',
                'meta_title'       => 'hospital-services',
                'keywords'         => 'hospital,clinical',
                'meta_description' => 'Hospital services description',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 10,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Clinical Services',
                'page_title'       => 'Clinical Services',
                'page_slug'        => 'clinical-services',
                'page_description' => 'Clinical services we provide.',
                'meta_title'       => 'clinical-services',
                'keywords'         => 'clinical,medical',
                'meta_description' => 'Clinical services details',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 11,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Support Services',
                'page_title'       => 'Support Services',
                'page_slug'        => 'support-services',
                'page_description' => 'Support services we provide.',
                'meta_title'       => 'support-services',
                'keywords'         => 'support,help',
                'meta_description' => 'Support services details',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 12,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Community Services',
                'page_title'       => 'Community Services',
                'page_slug'        => 'community-services',
                'page_description' => 'Details about our community programs.',
                'meta_title'       => 'community-services',
                'keywords'         => 'community,social',
                'meta_description' => 'Community services description',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 13,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Research & Publication',
                'page_title'       => 'Research & Publication',
                'page_slug'        => 'research-and-publication',
                'page_description' => 'Our research and published works.',
                'meta_title'       => 'research-publication',
                'keywords'         => 'research,publication',
                'meta_description' => 'Research and publication page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 14,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'For Patients',
                'page_title'       => 'For Patients',
                'page_slug'        => 'for-patients',
                'page_description' => 'Information for our patients.',
                'meta_title'       => 'for-patients',
                'keywords'         => 'patients,guide',
                'meta_description' => 'For patients page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 15,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Education and Training',
                'page_title'       => 'Education and Training',
                'page_slug'        => 'education-and-training',
                'page_description' => 'Educational and training programs.',
                'meta_title'       => 'education-training',
                'keywords'         => 'education,training',
                'meta_description' => 'Education and training details',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 16,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Performance',
                'page_title'       => 'Performance',
                'page_slug'        => 'performance',
                'page_description' => 'Our organizational performance details.',
                'meta_title'       => 'performance',
                'keywords'         => 'performance,report',
                'meta_description' => 'Performance page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 17,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Media & Events',
                'page_title'       => 'Media & Events',
                'page_slug'        => 'media-and-events',
                'page_description' => 'Our latest media updates and events.',
                'meta_title'       => 'media-events',
                'keywords'         => 'media,events',
                'meta_description' => 'Media and events page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 18,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Partner/Donor',
                'page_title'       => 'Partner/Donor',
                'page_slug'        => 'partner-donor',
                'page_description' => 'Our partners and donors.',
                'meta_title'       => 'partner-donor',
                'keywords'         => 'partner,donor',
                'meta_description' => 'Partner and donor page',
                'status'           => 1,
                'is_default'       => 0,
                'created_by'       => 1,
                'position'         => 19,
                'created_at'       => now(),
            ],
            [
                'page_name'        => 'Contact Us',
                'page_title'       => 'Contact Us',
                'page_slug'        => 'contact-us',
                'page_description' => 'Get in touch with us.',
                'meta_title'       => 'contact-us',
                'keywords'         => 'contact,help,support',
                'meta_description' => 'Contact us page',
                'status'           => 1,
                'is_default'       => 1,
                'created_by'       => 1,
                'position'         => 20,
                'created_at'       => now(),
            ],
            [
                'page_name'              => 'Privecy Policy',
                'page_title'             => 'Privecy Policy',
                'page_slug'              => 'privecy-policy',
                'page_description'       => 'This is Privecy Policy Us Page',
                'meta_title'             => 'privecy-policy',
                'keywords'               => 'privecy,privecy,privecy',
                'meta_description'       => 'this is privecy page',
                'status'                 => 1,
                'is_default'             => 1,
                'created_by'             => 1,
                'position'               => 3,
                'created_at'             => new \DateTime ?: new \DateTime
            ],
            [
                'page_name'              => 'Terms & Conditions',
                'page_title'             => 'Terms & Conditions',
                'page_slug'              => 'terms-&-conditions',
                'page_description'       => 'This is Terms & Conditions Page',
                'meta_title'             => 'terms-&-conditions',
                'keywords'               => 'terms-&-conditions,terms-&-conditions,terms-&-conditions',
                'meta_description'       => 'this is terms-&-conditions page',
                'status'                 => 1,
                'is_default'             => 1,
                'created_by'             => 1,
                'position'               => 3,
                'created_at'             => new \DateTime ?: new \DateTime
            ],
            
        ];

        foreach ($pages as $page) {
            Page::create($page);
        }
    }
}
